# Character X-Ray runtime compatibility spike (Windows).
#
# Copies an IKEMEN GO install into a DISPOSABLE sandbox (one subject character, one dummy, one stage, plus the Lua probe),
# runs a tiny controlled match there with a hard timeout, then reads the JSONL trace back and links its states to the static
# semantic index. Your real install and characters are only ever read.
#
# Success (all three must hold):
#   1. the sandboxed engine launched and produced a trace
#   2. the trace is valid JSONL with at least one frame and a meta event
#   3. at least one runtime StateNo of the subject maps to a static State object
#
# Example:
#   .\Run-XRaySpike.ps1 -IkemenRoot D:\IKEMEN -Subject Valentine -Dummy kfm -Stage stages/kfm.def
#
# Results are written to docs\xray-runtime-spike-result.md (which APIs this engine build exposed, hooks that registered, issues).

[CmdletBinding()]
param(
    [Parameter(Mandatory)][string]$IkemenRoot,
    [Parameter(Mandatory)][string]$Subject,
    [string]$Dummy = "kfm",
    [string]$Stage = "stages/kfm.def",
    [int]$Frames = 600,
    [int]$TimeoutSeconds = 90,
    [string[]]$ExtraArgs = @(),
    [switch]$NoAi,
    [switch]$KeepSandbox
)

$ErrorActionPreference = "Stop"
$windows = Split-Path $PSScriptRoot -Parent
$repo = Split-Path $windows -Parent
$resultPath = Join-Path $repo "docs\xray-runtime-spike-result.md"

Write-Host "=== X-Ray runtime spike ==="
Write-Host "Building the CLI..."
dotnet build (Join-Path $windows "IKEMENLab.Cli\IKEMENLab.Cli.csproj") -c Release --nologo -v q | Out-Null
if ($LASTEXITCODE -ne 0) { throw "CLI build failed" }
$cli = Get-ChildItem (Join-Path $windows "IKEMENLab.Cli\bin\Release") -Recurse -Filter "ikemenlab.exe" | Select-Object -First 1
if (-not $cli) { throw "ikemenlab.exe was not built" }

Write-Host "Preparing the sandbox (the real install is only read)..."
$prepJson = & $cli.FullName xray runtime-prepare --root $IkemenRoot --subject $Subject --dummy $Dummy --stage $Stage --frames $Frames
if ($LASTEXITCODE -ne 0) { throw "runtime-prepare failed: $prepJson" }
$prep = $prepJson | ConvertFrom-Json
$sandbox = $prep.sandbox
Write-Host "Sandbox: $sandbox"
foreach ($n in $prep.notes) { Write-Host "  note: $n" }

$engineArgs = @($prep.arguments)
if ($NoAi) {
    $engineArgs = $engineArgs | Where-Object { $_ -notin @("-p1.ai", "-p2.ai", "1") }
}
$engineArgs += $ExtraArgs
$commandLine = "$($prep.exe) $($engineArgs -join ' ')"
Write-Host "Launching: $commandLine"

$launched = $false
$exitInfo = "did not start"
$elapsed = 0
$timedOut = $false
try {
    $sw = [Diagnostics.Stopwatch]::StartNew()
    $proc = Start-Process -FilePath $prep.exe -ArgumentList $engineArgs -WorkingDirectory $sandbox -PassThru
    $launched = $true
    if (-not $proc.WaitForExit($TimeoutSeconds * 1000)) {
        $timedOut = $true
        Stop-Process -Id $proc.Id -Force -ErrorAction SilentlyContinue
        $exitInfo = "killed after ${TimeoutSeconds}s timeout"
    } else {
        $exitInfo = "exited with code $($proc.ExitCode)"
    }
    $sw.Stop()
    $elapsed = [math]::Round($sw.Elapsed.TotalSeconds, 1)
} catch {
    $exitInfo = "launch failed: $($_.Exception.Message)"
}
Write-Host "Engine $exitInfo ($elapsed s)"

$traceExists = Test-Path $prep.trace
$traceBytes = if ($traceExists) { (Get-Item $prep.trace).Length } else { 0 }
$logs = Get-ChildItem $sandbox -Filter "*.log" -ErrorAction SilentlyContinue

$report = $null
if ($traceExists -and $traceBytes -gt 0) {
    $reportJson = & $cli.FullName xray runtime-report (Join-Path $IkemenRoot "chars\$Subject") --trace $prep.trace --root $IkemenRoot
    if ($LASTEXITCODE -eq 0) { $report = $reportJson | ConvertFrom-Json }
}

$ok1 = $launched -and $traceExists -and $traceBytes -gt 0
$ok2 = $report -and $report.validTrace
$ok3 = $report -and $report.associatedAtLeastOneState

$md = New-Object System.Collections.Generic.List[string]
$md.Add("# X-Ray runtime spike result")
$md.Add("")
$md.Add("Generated by ``scripts/Run-XRaySpike.ps1`` on $(Get-Date -Format 'yyyy-MM-dd HH:mm') (machine-generated; do not hand-edit).")
$md.Add("")
$md.Add("| Check | Result |")
$md.Add("|---|---|")
$md.Add("| Disposable sandbox launched and produced a trace | $(if ($ok1) {'PASS'} else {'FAIL'}) |")
$md.Add("| Trace is valid JSONL with meta + frames | $(if ($ok2) {'PASS'} else {'FAIL'}) |")
$md.Add("| A runtime StateNo maps to a static State object | $(if ($ok3) {'PASS'} else {'FAIL'}) |")
$md.Add("")
$md.Add("- Command line: ``$commandLine``")
$md.Add("- Engine: $exitInfo ($elapsed s), timed out: $timedOut")
$md.Add("- Trace: $traceBytes bytes")
if ($logs) { $md.Add("- Engine logs in sandbox: $(($logs | ForEach-Object { $_.Name }) -join ', ')") }
if ($report) {
    $md.Add("- Frames: $($report.frames), state changes: $($report.stateChanges), life changes: $($report.lifeChanges)")
    if ($report.meta) {
        $md.Add("- Engine version reported: $($report.meta.engineVersion)  (probe $($report.meta.probeVersion), $($report.meta.platform))")
        $md.Add("- Hooks registered: $(($report.meta.hooksRegistered) -join ', ')")
        $md.Add("")
        $md.Add("## APIs this engine build exposed")
        $md.Add("")
        $md.Add("Supported: $(($report.meta.supported) -join ', ')")
        $md.Add("")
        $md.Add("Unsupported (written as null, never guessed): $(($report.meta.unsupported) -join ', ')")
    }
    $md.Add("")
    $md.Add("## Subject states seen at runtime")
    $md.Add("")
    $md.Add("| State | First frame | Frames | Static object |")
    $md.Add("|---|---|---|---|")
    foreach ($s in $report.states) { $md.Add("| $($s.stateNo)$(if ($s.commonState) {' (common)'}) | $($s.firstFrame) | $($s.frames) | $(if ($s.object) {$s.object} else {'not defined in the static index'}) |") }
    if ($report.issues.Count -gt 0) {
        $md.Add("")
        $md.Add("## Trace issues")
        $md.Add("")
        foreach ($i in $report.issues) { $md.Add("- line $($i.line): $($i.message)") }
    }
} else {
    $md.Add("")
    $md.Add("No usable trace. Things to check: the probe is at ``external/mods/xray_probe.lua`` in the sandbox and is also dofile()d from the top of ``external/script/main.lua``; look for ``probe_loaded`` in the trace; try ``-ExtraArgs`` with different match flags, and ``-KeepSandbox`` to inspect the engine log.")
}
Set-Content -Path $resultPath -Value $md -Encoding UTF8
Write-Host "Wrote $resultPath"

if (-not $KeepSandbox) { & $cli.FullName xray runtime-clean $sandbox | Out-Null } else { Write-Host "Sandbox kept: $sandbox" }

if ($ok1 -and $ok2 -and $ok3) { Write-Host "X-RAY RUNTIME SPIKE: PASS"; exit 0 }
Write-Host "X-RAY RUNTIME SPIKE: FAIL (see $resultPath)"
exit 1
