<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>IKEMENLab.Core</RootNamespace>
    <AssemblyName>IKEMENLab.Core</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="XRay\Runtime\xray_probe.lua" LogicalName="xray_probe.lua" />
    <EmbeddedResource Include="XRay\Runtime\xray_driver.lua" LogicalName="xray_driver.lua" />
    <EmbeddedResource Include="XRay\Runtime\xray_inject.lua" LogicalName="xray_inject.lua" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SharpCompress" Version="0.50.4" />
    <PackageReference Include="System.Text.Encoding.CodePages" Version="8.0.0" />
  </ItemGroup>

</Project>
